include: package:lints/recommended.yaml

analyzer:
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - discarded_futures
    - prefer_final_locals
    - sort_constructors_first
    - unawaited_futures
