name: Publish better_effect

on:
  push:
    tags:
      - 'better_effect-v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
      working-directory: packages/better_effect
